// Generated by https://quicktype.io

export interface PlacesResponse {
    type:        string;
    features:    Feature[];
    query:       number[];
    attribution: string;
}

export interface Feature {
    type:       string;
    properties: Properties;
    geometry:   Geometry;
    bbox:       number[];
    center:     number[];
    place_name: string;
    place_type: string[];
    relevance:  number;
    context?:   Context[];
    address?:   string;
    id:         string;
    text:       string;
}

export interface Context {
    ref:               string;
    country_code:      CountryCode;
    id:                string;
    text:              string;
    kind?:             Kind;
    "osm:place_type"?: string;
}

export enum CountryCode {
    Ch = "ch",
}

export enum Kind {
    AdminArea = "admin_area",
    Place = "place",
}

export interface Geometry {
    type:        string;
    coordinates: number[];
}

export interface Properties {
    ref:               string;
    country_code:      CountryCode;
    kind?:             string;
    "osm:place_type"?: string;
}
